In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
import pyproj
from shapely import geometry
import matplotlib.pyplot as plt
import earthpy


%matplotlib inline

### Criando as colunas para abrir o XYZ

In [2]:
gama_cols = 'KB DATA BARO UB THB COSMICO CTB UUP ALTURA KPERC eU eTH CTEXP UTHRAZAO X Y UKRAZAO MDT THKRAZAO LIVE_TIME CTCOR KCOR THCOR UCOR HORA GPSALT LATITUDE FIDUCIAL TEMP LONGITUDE'.split(" ")
gama_cols

['KB',
 'DATA',
 'BARO',
 'UB',
 'THB',
 'COSMICO',
 'CTB',
 'UUP',
 'ALTURA',
 'KPERC',
 'eU',
 'eTH',
 'CTEXP',
 'UTHRAZAO',
 'X',
 'Y',
 'UKRAZAO',
 'MDT',
 'THKRAZAO',
 'LIVE_TIME',
 'CTCOR',
 'KCOR',
 'THCOR',
 'UCOR',
 'HORA',
 'GPSALT',
 'LATITUDE',
 'FIDUCIAL',
 'TEMP',
 'LONGITUDE']

## Abrindo gama raw

In [3]:
gama_1105 = pd.read_csv('../../../database/xyz/1105_XYZ/1105/XYZ/1105_GamaLine.XYZ',names=gama_cols,delim_whitespace=True,skiprows=11,usecols=["X","Y","LATITUDE","LONGITUDE","KPERC","eU","eTH","CTCOR","UTHRAZAO","UKRAZAO","THKRAZAO","MDT"])
gama_1105.head(100)

,KPERC,eU,eTH,UTHRAZAO,X,Y,UKRAZAO,MDT,THKRAZAO,CTCOR,LATITUDE,LONGITUDE
0,1.02,1.11,13.00,0.1,292878.15,7624109.00,0.9,600.12,9.86,23.0,-21.473638,-46.998997
1,1.47,1.09,13.53,0.1,292876.59,7624190.38,0.8,599.47,9.77,24.2,-21.472903,-46.999002
2,1.82,1.15,14.97,0.1,292875.03,7624271.94,0.8,600.63,9.81,25.3,-21.472167,-46.999007
3,1.52,1.22,14.94,0.1,292874.16,7624353.33,0.7,602.72,9.96,25.5,-21.471432,-46.999005
4,1.34,1.15,13.11,0.1,292873.81,7624434.72,0.7,602.21,10.18,24.5,-21.470697,-46.998998
...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.42,1.03,12.71,0.1,292879.56,7631856.82,1.7,596.17,20.09,18.9,-21.403678,-46.998030
96,0.26,1.03,11.31,0.1,292879.24,7631935.81,1.8,599.09,21.22,18.1,-21.402965,-46.998023
97,0.31,0.94,11.22,0.1,292878.24,7632014.80,1.9,603.28,22.36,18.5,-21.402252,-46.998023
98,0.28,0.97,10.40,0.1,292877.23,7632093.78,2.0,606.98,23.35,19.0,-21.401538,-46.998023
99,0.22,0.98,8.70,0.1,292875.54,7632172.76,2.0,613.81,24.04,18.2,-21.400825,-46.998030

In [4]:
gama_1105

,KPERC,eU,eTH,UTHRAZAO,X,Y,UKRAZAO,MDT,THKRAZAO,CTCOR,LATITUDE,LONGITUDE
0,1.020,1.110,13.000,0.100,292878.15,7624109.00,0.900,600.12,9.860,23.000,-21.473638,-46.998997
1,1.470,1.090,13.530,0.100,292876.59,7624190.38,0.800,599.47,9.770,24.200,-21.472903,-46.999002
2,1.820,1.150,14.970,0.100,292875.03,7624271.94,0.800,600.63,9.810,25.300,-21.472167,-46.999007
3,1.520,1.220,14.940,0.100,292874.16,7624353.33,0.700,602.72,9.960,25.500,-21.471432,-46.999005
4,1.340,1.150,13.110,0.100,292873.81,7624434.72,0.700,602.21,10.180,24.500,-21.470697,-46.998998
...,...,...,...,...,...,...,...,...,...,...,...,...
1173979,0.509,0.373,15.020,0.059,602874.51,7526876.45,2.343,571.23,39.739,5.532,-22.360971,-44.000843
1173980,0.315,0.549,14.462,0.061,602872.51,7526806.94,2.877,578.02,47.230,5.043,-22.361599,-44.000858
1173981,0.282,1.005,17.569,0.063,602871.22,7526737.54,3.712,581.39,58.969,6.422,-22.362226,-44.000866
1173982,0.399,1.347,20.376,0.065,602870.35,7526668.02,5.155,577.24,79.214,8.287,-22.362854,-44.000870
1173983,0.297,1.603,20.764,0.067,602870.30,7526598.50,8.095,566.03,120.323,9.324,-22.363482,-44.000866

## Retirando as linhas de cabeÃ§alho

In [5]:
gama_1105.dropna(inplace=False)

,KPERC,eU,eTH,UTHRAZAO,X,Y,UKRAZAO,MDT,THKRAZAO,CTCOR,LATITUDE,LONGITUDE
0,1.020,1.110,13.000,0.100,292878.15,7624109.00,0.900,600.12,9.860,23.000,-21.473638,-46.998997
1,1.470,1.090,13.530,0.100,292876.59,7624190.38,0.800,599.47,9.770,24.200,-21.472903,-46.999002
2,1.820,1.150,14.970,0.100,292875.03,7624271.94,0.800,600.63,9.810,25.300,-21.472167,-46.999007
3,1.520,1.220,14.940,0.100,292874.16,7624353.33,0.700,602.72,9.960,25.500,-21.471432,-46.999005
4,1.340,1.150,13.110,0.100,292873.81,7624434.72,0.700,602.21,10.180,24.500,-21.470697,-46.998998
...,...,...,...,...,...,...,...,...,...,...,...,...
1173979,0.509,0.373,15.020,0.059,602874.51,7526876.45,2.343,571.23,39.739,5.532,-22.360971,-44.000843
1173980,0.315,0.549,14.462,0.061,602872.51,7526806.94,2.877,578.02,47.230,5.043,-22.361599,-44.000858
1173981,0.282,1.005,17.569,0.063,602871.22,7526737.54,3.712,581.39,58.969,6.422,-22.362226,-44.000866
1173982,0.399,1.347,20.376,0.065,602870.35,7526668.02,5.155,577.24,79.214,8.287,-22.362854,-44.000870
1173983,0.297,1.603,20.764,0.067,602870.30,7526598.50,8.095,566.03,120.323,9.324,-22.363482,-44.000866

## Salvando o arquivo bruto GamaLine_XYZ

In [6]:
gama_1105.to_csv('../../../database/csv/gama/gama_1105_sraw.csv', index=False)

### Agora com o xyz magnetomÃ©trico

In [7]:
mag_cols = 'DATA BARO ALTURA X Y MDT HORA GPSALT LATITUDE FIDUCIAL LONGITUDE ALTURA_1 IGRF MAGBASE MAGBRU MAGCOM MAGCOR MAGIGRF MAGMIC MAGNIV'.split(" " )
mag_cols

['DATA',
 'BARO',
 'ALTURA',
 'X',
 'Y',
 'MDT',
 'HORA',
 'GPSALT',
 'LATITUDE',
 'FIDUCIAL',
 'LONGITUDE',
 'ALTURA_1',
 'IGRF',
 'MAGBASE',
 'MAGBRU',
 'MAGCOM',
 'MAGCOR',
 'MAGIGRF',
 'MAGMIC',
 'MAGNIV']

In [8]:
mag_1105 = pd.read_csv('../../../database/xyz/1105_XYZ/1105/XYZ/1105_MagLine.XYZ',names=mag_cols,delim_whitespace=True,skiprows=11,usecols=["X","Y","LATITUDE","LONGITUDE","MAGCOM","MAGCOR","MAGIGRF","MAGMIC","MAGNIV","MDT"])
mag_1105.head(100)

,X,Y,MDT,LATITUDE,LONGITUDE,MAGCOM,MAGCOR,MAGIGRF,MAGMIC,MAGNIV
0,292879.66,7624043.90,609.44,-21.474226,-46.998990,23154.640,23123.693,49.882,23113.580,23119.835
1,292879.49,7624052.04,609.53,-21.474153,-46.998991,23155.182,23124.236,50.469,23114.171,23120.439
2,292879.32,7624060.18,609.60,-21.474079,-46.998991,23155.734,23124.789,50.987,23114.677,23120.958
3,292879.15,7624068.32,609.66,-21.474006,-46.998992,23156.180,23125.236,51.473,23115.181,23121.473
4,292878.98,7624076.47,609.71,-21.473932,-46.998993,23156.659,23125.715,51.945,23115.658,23121.963
...,...,...,...,...,...,...,...,...,...,...
95,292875.91,7624816.99,602.45,-21.467245,-46.998931,23067.344,23036.446,-38.866,23025.277,23032.544
96,292876.05,7624825.15,602.33,-21.467172,-46.998929,23066.365,23035.468,-39.895,23024.253,23031.524
97,292876.18,7624833.31,602.22,-21.467098,-46.998926,23065.414,23034.517,-40.851,23023.303,23030.577
98,292876.32,7624841.47,602.12,-21.467024,-46.998924,23064.628,23033.731,-41.762,23022.396,23029.676
99,292876.47,7624849.63,602.02,-21.466951,-46.998922,23063.710,23032.814,-42.651,23021.506,23028.791

### Os dados magnetomÃ©tricos possuem uma frequÃªncia 10x maior que do gamaespectomÃ©tricos, gerando 10x mais pontos, basicamente

In [9]:
mag_1105.dropna(inplace=False)

,X,Y,MDT,LATITUDE,LONGITUDE,MAGCOM,MAGCOR,MAGIGRF,MAGMIC,MAGNIV
0,292879.66,7624043.90,609.44,-21.474226,-46.998990,23154.640,23123.693,49.882,23113.580,23119.835
1,292879.49,7624052.04,609.53,-21.474153,-46.998991,23155.182,23124.236,50.469,23114.171,23120.439
2,292879.32,7624060.18,609.60,-21.474079,-46.998991,23155.734,23124.789,50.987,23114.677,23120.958
3,292879.15,7624068.32,609.66,-21.474006,-46.998992,23156.180,23125.236,51.473,23115.181,23121.473
4,292878.98,7624076.47,609.71,-21.473932,-46.998993,23156.659,23125.715,51.945,23115.658,23121.963
...,...,...,...,...,...,...,...,...,...,...
11639595,602870.41,7526564.70,574.08,-22.363787,-44.000863,23229.815,23228.488,-25.681,23211.627,23224.542
11639596,602870.46,7526558.68,573.60,-22.363842,-44.000862,23229.896,23228.570,-25.654,23211.641,23224.616
11639597,602870.50,7526553.15,573.19,-22.363892,-44.000861,23229.980,23228.655,-25.627,23211.673,23224.710
11639598,602870.53,7526548.22,572.86,-22.363936,-44.000861,23230.067,23228.742,-25.608,23211.685,23224.788
11639599,602870.56,7526543.98,572.61,-22.363974,-44.000860,23230.160,23228.836,-25.595,23211.693,23224.862

In [10]:
mag_1105.to_csv('../../../database/csv/mag/mag_1105_sraw.csv', index=False)